### ISSUE TITLE
My Cmake can't find TBB::tbb and TBB::tbbmalloc

### ISSUE THREAD

**Issue by tanmayd26** [oneapi-src/oneTBB#1277]
`CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:14 (add_executable):
  Target "StateEstimator" links to target "TBB::tbb" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:14 (add_executable):
  Target "StateEstimator" links to target "TBB::tbbmalloc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
`

I have it installed here:
/usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so
/usr/lib/x86_64-linux-gnu/libtbbmalloc.so
/usr/lib/x86_64-linux-gnu/libtbb.so.2
/usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
/usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so.2
/usr/lib/x86_64-linux-gnu/libtbb.so

`
libtbbmalloc_proxy.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbbmalloc_proxy.so.2
	libtbbmalloc_proxy.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbbmalloc_proxy.so
	libtbbmalloc.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbbmalloc.so.2
	libtbbmalloc.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbbmalloc.so
	libtbb.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbb.so.2
	libtbb.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libtbb.so

`

Can anyone help been struggling to get a working solution.

**Comment by isaevil** [comment]
@tanmayd26 do you have reproducer steps? I am mostly interested in CMakelists.txt. Did you use `find_package(TBB)` as error message suggested?

**Comment by tanmayd26** [comment]
Yes here,
```
find_package(Eigen3 REQUIRED)
find_package(GeographicLib REQUIRED)
find_package (Boost REQUIRED COMPONENTS system filesystem thread chrono date_time atomic serialization regex timer)
include_directories(SYSTEM ${Boost_LIBRARY_DIRS})

include_directories(include ${catkin_INCLUDE_DIRS})
include_directories(SYSTEM ${EIGEN3_INCLUDE_DIR})

find_package(GTSAM)
if(GTSAM_FOUND)
  find_package(TBB REQUIRED)
  include_directories(SYSTEM ${GTSAM_INCLUDE_DIR} "/usr/local/include" ${Boost_INCLUDE_DIRS}) 

  add_executable(StateEstimator StateEstimator.cpp)
message(==========${GeographicLib_LIBRARY_DIRS}/${GeographicLib_LIBRARIES})
  target_link_libraries(StateEstimator ${catkin_LIBRARIES} ${ROS_LIBRARIES} gtsam ${GeographicLib_LIBRARY_DIRS}/libGeographic.so ${TBB_LIBRARIES} ar_diagnostics ${Boost_LIBRARIES})
  add_dependencies(StateEstimator autorally_msgs_gencpp)

  install(TARGETS StateEstimator
          ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
          LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
          RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
endif()

```

**Comment by tanmayd26** [comment]
I got some extra analysis done. I added a message to print the location and yes it knows that tbb is here in this location.
`-- TBB_LIBRARIES: /usr/lib/x86_64-linux-gnu/libtbb.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbb.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so
==========/usr/local/lib/GeographicLib
CMake Warning at autorally/autorally_core/src/CameraAutoBalance/CMakeLists.txt:23 (message):
  Could not find FlyCapture library.  Will not build CameraAutoBalance for
  Point Grey cameras


CMake Warning at autorally/autorally_core/src/CameraAutoBalance/CMakeLists.txt:44 (message):
  Could not find Spinnaker library.  Will not build CameraAutoBalance for
  FLIR cameras


-- +++ processing catkin package: 'autorally_control'
-- ==> add_subdirectory(autorally/autorally_control)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.55.0")  
-- Installing devel-space wrapper /home/tanmay/catkin_ws/src/autorally/autorally_control/src/gpsWaypoint/GenerateWaypoints to /home/tanmay/catkin_ws/devel/lib/autorally_control
-- Found CUDA: /usr (found version "10.1") 
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configuring done
CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:17 (add_executable):
  Target "StateEstimator" links to target "TBB::tbb" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:17 (add_executable):
  Target "StateEstimator" links to target "TBB::tbbmalloc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`

**Comment by tanmayd26** [comment]
CMake Error: The source directory "/home/tanmay/--debug-find" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
``` cmake --debug-find catkin_ws/src/autorally/
```

**Comment by tanmayd26** [comment]
```
/opt/ros/noetic/share/catkin/cmake/em/order_packages.cmake.em:2:1: error: RuntimeError: ImportError: "from catkin_pkg.topological_order import topological_order" failed: cannot import name 'Sequence' from 'collections' (/home/tanmay/anaconda3/lib/python3.11/collections/__init__.py)
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
<root>:1:1: from this context
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/catkin_pkg/topological_order.py", line 39, in <module>
    from .packages import find_packages
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/catkin_pkg/packages.py", line 38, in <module>
    from .package import _get_package_xml
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/catkin_pkg/package.py", line 44, in <module>
    from catkin_pkg.condition import evaluate_condition
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/catkin_pkg/condition.py", line 17, in <module>
    import pyparsing as pp
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/pyparsing/__init__.py", line 140, in <module>
    from .core import __diag__, __compat__
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/pyparsing/core.py", line 31, in <module>
    from pathlib import Path
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/home/tanmay/anaconda3/lib/python3.11/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 5767, in <module>
    if __name__ == '__main__': main()
                               ^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 5764, in main
    exitCode = invoke(sys.argv[1:], executable=sys.argv[0], errors=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 5737, in invoke
    error = interpreter.go(
            ^^^^^^^^^^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4335, in go
    error = self.protect(name, method, file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4358, in protect
    callable(*args, **kwargs)
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4385, in file
    self.fileChunks(file, config.buffering, locals)
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4429, in fileChunks
    while not self.safe(scanner, done, locals):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4487, in safe
    self.handle(sys.exc_info())
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4462, in safe
    return self.parse(scanner, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4507, in parse
    self.run(token, locals)
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4748, in run
    token.run(self, locals)
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 2503, in run
    interpreter.execute(self.code, locals)
  File "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py", line 4811, in execute
    self.execFunc(statements, self.globals, locals)
  File "<string>", line 10, in <module>
RuntimeError: ImportError: "from catkin_pkg.topological_order import topological_order" failed: cannot import name 'Sequence' from 'collections' (/home/tanmay/anaconda3/lib/python3.11/collections/__init__.py)
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/home/tanmay/catkin_generated/env_cached.sh
  "/home/tanmay/anaconda3/bin/python3"
  "/home/tanmay/anaconda3/lib/python3.11/site-packages/em.py" "--raw-errors"
  "-F" "/home/tanmay/catkin_generated/order_packages.py" "-o"
  "/home/tanmay/catkin_generated/order_packages.cmake"
  "/opt/ros/noetic/share/catkin/cmake/em/order_packages.cmake.em") returned
  error code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:35 (em_expand)
  CMakeLists.txt:69 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/tanmay/CMakeFiles/CMakeOutput.log".
See also "/home/tanmay/CMakeFiles/CMakeError.log".

```

This is what I got after running `cmake --debug-find /home/tanmay/catkin_ws/src/`. This is weird because I am running it in conda. I don't get this error after running catkin_make in my catkin workspace.

**Comment by tanmayd26** [comment]
`CMake Error: The source "/home/tanmay/catkin_ws/src/autorally/autorally_control/CMakeLists.txt" does not match the source "/home/tanmay/catkin_ws/src/autorally/autorally/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.`

**Comment by tanmayd26** [comment]
```
(my_ros_env) tanmay@tanmay-lab-ubuntu:~/catkin_ws/build$ cmake --debug-find /home/tanmay/catkin_ws/src
-- Using CATKIN_DEVEL_PREFIX: /home/tanmay/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/tanmay/catkin_ws/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 13 packages in topological order:
-- ~~  - autorally (metapackage)
-- ~~  - autorally_description
-- ~~  - autorally_gazebo
-- ~~  - pointgrey_camera_description
-- ~~  - statistics_msgs
-- ~~  - image_exposure_msgs
-- ~~  - autorally_msgs
-- ~~  - autorally_util
-- ~~  - imu_3dm_gx4
-- ~~  - wfov_camera_msgs
-- ~~  - pointgrey_camera_driver
-- ~~  - autorally_core
-- ~~  - autorally_control
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'autorally'
-- ==> add_subdirectory(autorally/autorally)
-- +++ processing catkin package: 'autorally_description'
-- ==> add_subdirectory(autorally/autorally_description)
-- +++ processing catkin package: 'autorally_gazebo'
-- ==> add_subdirectory(autorally/autorally_gazebo)
-- +++ processing catkin package: 'pointgrey_camera_description'
-- ==> add_subdirectory(pointgrey_camera_driver/pointgrey_camera_description)
-- +++ processing catkin package: 'statistics_msgs'
-- ==> add_subdirectory(pointgrey_camera_driver/statistics_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- statistics_msgs: 1 messages, 0 services
-- +++ processing catkin package: 'image_exposure_msgs'
-- ==> add_subdirectory(pointgrey_camera_driver/image_exposure_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- image_exposure_msgs: 3 messages, 0 services
-- +++ processing catkin package: 'autorally_msgs'
-- ==> add_subdirectory(autorally/autorally_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: thread 
-- autorally_msgs: 15 messages, 0 services
-- +++ processing catkin package: 'autorally_util'
-- ==> add_subdirectory(autorally/autorally_util)
-- +++ processing catkin package: 'imu_3dm_gx4'
-- ==> add_subdirectory(imu_3dm_gx4)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- imu_3dm_gx4: 1 messages, 0 services
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
-- +++ processing catkin package: 'wfov_camera_msgs'
-- ==> add_subdirectory(pointgrey_camera_driver/wfov_camera_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- wfov_camera_msgs: 3 messages, 0 services
-- +++ processing catkin package: 'pointgrey_camera_driver'
-- ==> add_subdirectory(pointgrey_camera_driver/pointgrey_camera_driver)
-- libflycapture found in system library path
-- libflycapture library: /usr/lib/libflycapture.so.2
-- libflycapture copied from: /usr/lib/libflycapture.so.2.13.3.31 into /home/tanmay/catkin_ws/devel/lib/libflycapture.so.2
-- +++ processing catkin package: 'autorally_core'
-- ==> add_subdirectory(autorally/autorally_core)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Reading /usr/local/lib/cmake/GeographicLib/geographiclib-config.cmake
-- GeographicLib configuration, version 1.49
--   ${GeographicLib_LIBRARIES} set to shared library
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: chrono date_time filesystem regex serialization system thread timer 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.65") found components: serialization system filesystem thread program_options date_time timer chrono regex 
-- Found Intel TBB
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
-- Found Intel TBB
==========/usr/local/lib/GeographicLib
CMake Warning at autorally/autorally_core/src/CameraAutoBalance/CMakeLists.txt:44 (message):
  Could not find Spinnaker library.  Will not build CameraAutoBalance for
  FLIR cameras


-- +++ processing catkin package: 'autorally_control'
-- ==> add_subdirectory(autorally/autorally_control)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.55.0")  
-- Installing devel-space wrapper /home/tanmay/catkin_ws/src/autorally/autorally_control/src/gpsWaypoint/GenerateWaypoints to /home/tanmay/catkin_ws/devel/lib/autorally_control
-- Configuring done
CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:24 (add_executable):
  Target "StateEstimator" links to target "TBB::tbb" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at autorally/autorally_core/src/StateEstimator/CMakeLists.txt:24 (add_executable):
  Target "StateEstimator" links to target "TBB::tbbmalloc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Warning at autorally/autorally_core/src/CameraAutoBalance/CMakeLists.txt:12 (add_library):
  Cannot generate a safe runtime search path for target
  CameraAutoBalancePtGrey because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libflycapture.so.2] in /usr/lib may be hidden by files in:
      /home/tanmay/catkin_ws/devel/lib

  Some of these libraries may not be found correctly.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by nofuturre** [comment]
@tanmayd26 is this issue still relevant?

**Comment by tanmayd26** [comment]
No I will close it.
