### ISSUE TITLE
Variable not initialized in gcc_ia32_common.h

### ISSUE THREAD

**Issue by Unril** [oneapi-src/oneTBB#31]
While running tbb under memory sanitizer.

`MemorySanitizer: use-of-uninitialized-value /tbb/include/tbb/machine/gcc_ia32_common.h:79:81 in tbb::internal::cpu_ctl_env::operator!=(tbb::internal::cpu_ctl_env const&) const`

```
    #0 0x9b1125 in tbb::internal::cpu_ctl_env::operator!=(tbb::internal::cpu_ctl_env const&) const /tbb/include/tbb/machine/gcc_ia32_common.h:79:81
    #1 0x9b1125 in tbb::internal::cpu_ctl_env_helper::set_env(tbb::task_group_context const*) /tbb/src/tbb/scheduler.h:711
    #2 0x9b1125 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) /tbb/src/tbb/custom_scheduler.h:427
    #3 0x9a62e3 in tbb::internal::generic_scheduler::local_spawn_root_and_wait(tbb::task*, tbb::task*&) /tbb/src/tbb/scheduler.cpp:677:5
    #4 0x7b6aa6 in tbb::task::spawn_root_and_wait(tbb::task&) /tbb/include/tbb/task.h:749:30
```

**Comment by ntfshard** [comment]
Hello
Could you please share an information about testing environment and (if possible) provide us a reproducer

**Comment by ivankochin** [comment]
This code was removed in one of the releases. Please, reopen the issue if you observe still observe it in oneTBB 2021.
