### ISSUE TITLE
Unable to import a package due to an undefined TBB symbol

### ISSUE THREAD

**Issue by Amir-Arsalan** [oneapi-src/oneTBB#375]
I installed [libtbb](https://packages.ubuntu.com/bionic/libtbb-dev) in Ubuntu 18.04 in a Singularity container via `apt-get install libtbb-dev`. I installed another package (CGAL) that seems to be using TBB for some operations. However, I get the following error when I'm trying to import a class of the CGAL pacakge in Python. Does anyone know how I can resolve this issue?

```
>>> from CGAL.CGAL_AABB_tree import AABB_tree_Triangle_3_soup
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/CGAL/CGAL_AABB_tree.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.7/dist-packages/CGAL/_CGAL_AABB_tree.so: undefined symbol: _ZN3tbb8internal25concurrent_vector_base_v3D2Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/CGAL/CGAL_AABB_tree.py", line 20, in <module>
    _CGAL_AABB_tree = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/CGAL/CGAL_AABB_tree.py", line 19, in swig_import_helper
    return importlib.import_module('_CGAL_AABB_tree')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_CGAL_AABB_tree'

```

I thought this might be related to the TBB version so I installed a more recent version of TBB via the following but I still get the same error message. I search on the internet for the error message but so far I don't find anything that can help me address this issue:

```
apt-get purge -y libtbb-dev
cd /
git clone https://github.com/wjakob/tbb.git
cd tbb
cd build
cmake ..
make -j 60
make install
rm -rf /tbb
```

**Comment by alexey-katranov** [comment]
`_ZN3tbb8internal25concurrent_vector_base_v3D2Ev` is relatively old symbol. It seems either really old TBB is somewhere available or TBB is not found at all. To check the first supposition you can try to find over your file system or installed packages that no any other libtbb.so.2 is present? Additionally, you can try [`strace`](https://man7.org/linux/man-pages/man1/strace.1.html) tool but it can produce the heavy log.

**Comment by Amir-Arsalan** [comment]
Thank you. I installed a new version of TBB and things work fine now.
