### ISSUE TITLE
tbb4py from PyPI: ModuleNotFoundError: No module named '_api'

### ISSUE THREAD

**Issue by ogrisel** [oneapi-src/oneTBB#93]
The linux binary wheel from PyPI does not seem to be functional (when installed in a new virtualenv):

```python-traceback
ogrisel@ici:~$ source /tmp/venv36/bin/activate
(venv36) ogrisel@ici:~$ python -m pip install tbb4py tbb
[snip]
(venv36) ogrisel@ici:~$ python -m tbb
Traceback (most recent call last):
  File "/tmp/venv36/lib/python3.6/site-packages/tbb/api.py", line 43, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: libimf.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/python3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/python3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/tmp/venv36/lib/python3.6/site-packages/tbb/__init__.py", line 30, in <module>
    from .api import  *
  File "/tmp/venv36/lib/python3.6/site-packages/tbb/api.py", line 46, in <module>
    _api = swig_import_helper()
  File "/tmp/venv36/lib/python3.6/site-packages/tbb/api.py", line 45, in swig_import_helper
    return importlib.import_module('_api')
  File "/opt/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_api'
```

Here are the details of the versions installed by pip in that venv:

```
(venv36) ogrisel@ici:~$ python -m pip show tbb tbb4py
Name: tbb
Version: 2019.0
Summary: High level abstract threading library
Home-page: https://software.intel.com/en-us/
Author: Intel Corporation
Author-email: scripting@intel.com
License: Proprietary - Intel
Location: /tmp/venv36/lib/python3.6/site-packages
Requires: 
---
Name: tbb4py
Version: 2019.0
Summary: Composable Parallelism for Python with Intel(R) TBB
Home-page: https://software.intel.com/en-us/blogs/2016/04/04/unleash-parallel-performance-of-python-programs
Author: Intel Corporation
Author-email: scripting@intel.com
License: Proprietary - Intel
Location: /tmp/venv36/lib/python3.6/site-packages
Requires: tbb
```

**Comment by anton-malakhov** [comment]
Looks like it was built with Intel compiler and the runtime dependency is not specified. Please try to work it around with `pip install icc-rt`

**Comment by ogrisel** [comment]
Thanks @anton-malakhov, I confirm that installing icc-rt solves the issue.

So basically we just need:

- adding the icc-rt dependency to the tbb4py wheels for all supported python version;
- making and uploading to pypi the tbb4py wheel for Python 3.7.

I live this issue open to track these two steps.

**Comment by ogrisel** [comment]
And updating the CI to make sure that it's possible to import the "tbb" from a new python venv where only `pip install /path/to/generated/tbb4py-XXX.whl` was executed.

**Comment by anton-malakhov** [comment]
You are absolutely right w.r.t. validation of the packages we upload, it looks like none of the validation/testing stages caught it since we didn't have isolated environment, so icc-rt was always in the env.
The first step will be different for the next release though, as we don't actually need that dependence, it will be eliminated with the next TBB release. I'll ask if we can re-publish existing packages of current version with additional dependence

**Comment by anton-malakhov** [comment]
It should be fixed in 2019.1 (and integrated in the unit test :) ). It is a matter of publishing PyPi packages now.

**Comment by ogrisel** [comment]
https://pypi.org/search/?q=tbb only shows tbb and tbb4py 2019.0 still.

**Comment by ogrisel** [comment]
@anton-malakhov any news on this? @jeremiedbb and I would like to be able to use tbb4py from https://github.com/joblib/threadpoolctl.

**Comment by jeremiedbb** [comment]
wheels for python 3.7 are missing on pypi, although tbb4py can be installed via conda.

**Comment by anton-malakhov** [comment]
Hi @tomashek, any idea when and whether tbb4py will be available on pypi?

**Comment by anton-potapov** [comment]
@AlexVeprev could you please take  a look ?

**Comment by AlexVeprev** [comment]
https://pypi.org/search/?q=tbb now contains the latest version (2021.4.0), it should work.
Quick check in my env:
```
/tmp> python3 --version
Python 3.8.10
/tmp> python3 -m pip install tbb4py
Collecting tbb4py
  Downloading tbb4py-2021.4.0-py38-none-manylinux1_x86_64.whl (318 kB)
     |████████████████████████████████| 318 kB 458 kB/s
Collecting tbb==2021.4.0
  Downloading tbb-2021.4.0-py2.py3-none-manylinux1_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 1.6 MB/s
Installing collected packages: tbb, tbb4py
Successfully installed tbb-2021.4.0 tbb4py-2021.4.0
/tmp> python3 -m tbb -h
usage: python3 -m tbb [-h] [--ipc] [-a] [--allocator-huge-pages] [-p P] [-b] [-v] [-m] name ...

Run your Python script in context of tbb.Monkey, which replaces standard Python pools and threading layer of Intel(R) oneAPI Math Kernel Library (oneMKL) by implementation based on Intel(R) oneAPI Threading
Building Blocks (oneTBB). It enables multiple parallel tasks to be executed on the same thread pool and coordinate number of threads across multiple processes thus avoiding overheads from oversubscription.

positional arguments:
  name                  Script or module name
  args                  Command line arguments

optional arguments:
  -h, --help            show this help message and exit
  --ipc                 Enable inter-process (IPC) coordination between oneTBB schedulers (default: False)
  -a, --allocator       Enable oneTBB scalable allocator as a replacement for standard memory allocator (default: False)
  --allocator-huge-pages
                        Enable huge pages for oneTBB allocator (implies: -a) (default: False)
  -p P, --max-num-threads P
                        Initialize oneTBB with P max number of threads per process (default: 44)
  -b, --benchmark       Block oneTBB initialization until all the threads are created before continue the script. This is necessary for performance benchmarks that want to exclude lazy scheduler
                        initialization effects from the measurements (default: False)
  -v, --verbose         Request verbose and version information (default: False)
  -m                    Executes following as a module (default: False)
```
